name: java-webapp-gha

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "oidc-integration"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read


#env:
#  APP_VERSION: 2.0.0
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_webapp:
      
    if: ${{ true }}
    runs-on: ubuntu-latest
    env:
      MVN_VERSION: 3.9.9
      MVN_REPO: 'ych-maven'
      OIDC_AUDIENCE: 'github-yann-demo'
      OIDC_PROVIDER: 'github-yann'
    steps:
      - uses: actions/checkout@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
           JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: ${{ env.OIDC_PROVIDER }} 
          oidc-audience: ${{ env.OIDC_AUDIENCE }} 
          disable-auto-build-publish: false 
          disable-job-summary: false 
          
      - name: Setup Maven ${{ env.MVN_VERSION }}
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 23 
          maven-version: ${{ env.MVN_VERSION }} 

      - name: Ping Artifactory
        run: |
            jf --version
            jf config show
            jf rt ping
            env
            
      - name: Configure JFrog CLI with Maven client
        run: | 
          jf mvnc \
                  --repo-resolve-releases=${{ env.MVN_REPO }}	\
                  --repo-resolve-snapshots=${{ env.MVN_REPO }}	\
                  --repo-deploy-releases=${{ env.MVN_REPO }} \
                  --repo-deploy-snapshots=${{ env.MVN_REPO }}

#      - name: Curation 
#        run:  jf curation-audit  --working-dirs=src

#      - name: Scan dependencies
#        run:  jf audit --working-dirs=src 
        
      - name: Build webapp and scan generated artifact before upload
        run: jf mvn clean install -f src/  --no-transfer-progress

      - name: Collect Build information
        run: |
          # Collect environment variables for the build
          jf rt bce 
          # Collect VCS details from git and add them to the build
          jf rt bag
          
      - name: Run test 
        run: echo running tests ...

